### PR TITLE
stop building with circle-ci

### PR DESCRIPTION
**Pull request by aborsu**

### CODE REVIEW

**Comment by SagaStalin** [comment]
<KGB>

**Comment by SagaStalin** [comment]
<KGB>

**Comment by satblip** [comment]
LGTM

**Comment by SagaStalin** [comment]
<KGB>5ab2b49b1845ca61fb52c60eb723a751cab62136
>Merge branch 'master' into docker

Status must start with:
docs, feat, fix, perf, refactor, revert, style, test
Conform status to `<type>(<scope>): <subject>` pattern

**Pull request merged**
