### PR TITLE
feat(angularjs): chore

### PR DESCRIPTION
**Pull request by aborsu**

### CODE REVIEW

**Comment by satblip** [comment]
@aborsu rajoute le au Readme aussi ;)

**Comment by aborsu** [comment]
@satblip done

**Comment by aborsu** [comment]
[XS: Add chore to Kgitb types](https://trello.com/c/5YVl67lM/313-xs-add-chore-to-kgitb-types)

**Review by satblip — APPROVED** [review]
LGTM

**Pull request merged**
